services:
  postgres:
    image: postgres
    env_file: .env
    ports:
      - 5432:5432
  adminer:
    image: adminer
    ports:
      - 8080:8080
  backend:
    build:
      context: .
    env_file: .env
    ports:
      - 8000:8000
    entrypoint: bash -c "
      prisma generate &&
      prisma migrate dev &&
      uvicorn src.main:app --host 0.0.0.0 --port 8000
      "
